from ciphers.decryption import Decryption
from ciphers.vigenere import Vigenere


def test_encrypt():
    plaintext = 'attack at dawn'
    key = 'lemon'
    vigenere = Vigenere(plaintext, key, 5)
    ciphertext = "lxfopv mh oeib"
    assert(vigenere.encrypt() == ciphertext)


def test_decrypt():
    ciphertext = "lxfopv mh oeib"
    key = "lemon"
    vigenere = Vigenere(ciphertext, key, 5)
    decryption = Decryption("attack at dawn", "lemon")
    decryptions = vigenere.decrypt()
    assert(decryptions[0].text == decryption.text)


def test_decrypt_no_key():
    # ciphertext = "QW RHITJC, WP MCX UVLHX, KFT TKIQI SUJCCMWCC UHF R BTB'J QXWPX P UQFB VWVZXTG KJ WBG GMHLSUJGDG QW IAS YMBX XZPINSU MU KJZAW KG RWBBM UWXB NC VONC P ACE QR VYC XARYYIBQ RBYXQVZTT CH KPGZA. CH ORL VOP ZT O XMDW EZRXSSP UWH KJ CHH R VHCF FJLPCEB TBF Y ZCQU UTHJVP, KJF XL PFR ACPVQI WP FXL FVYABBIJ LBHJ MIAST KTG CEB PCOVL, TCZRWYIN RD VKJ UKWGEBH OPU UXOTCCHL KE IAS GPTLSPTC HT YGH TQVQ, KJF WTG EMI UQK P GQLLS VGRPI, C QDNBF KXGR, YCW C QDNBF ZDWM; CMTQVCW TG EM TAQLLI CH YIMSPKGDG VF RBJKC SNHKVQ PWNC HTJG Y GOVZMC WH RWX FFKTLHKT ABTG GH IPUCGFWPVB, CT RWXFG GH ZCTI HT KFT FWUC FWNZRPKM MGGMIGJ LAWEY PECPV RTB RQHNFG Y VCWERGR'U NDLWVZMC WP RWX YFPAW. ZL T HICT FGGSQEWE RWX KUCPE EZRXSSP KJLH SC HBG UXEZKEE TBF YQES KM MOMV PKAU DDK VYC WSHVLHX QW IAS WJPZ, VVPVHNP PL VYC BRGRJ VWVZXTG OLQI PG RWX HRRWXF FD FOPP WXONKFN QJZJSKSP. P FCTC FIUK QX UKPDGU RLS JKXMGHIU; XM OLQI PG Y KOEV DY IFMS TKXFIXFU YCW IFMS PTVCSXFU, TEGG GIL YZQSHA NGAE EFKT HQ LPNUJK PGR ZRH JKIRJX DV XGSHWCRMWXV; TBF LD GYVCIGSUJ PGR UCABQCTW, BQ JDOS WMG OPU PIDTVAXTHKFL HT SCPNHA GC OTK DK NZRTKOVLPT, PF RTDCTGIR HFP UIKCBXGU LN FOVVPXTZ GPDLDGIGIR ERL ICUJGQEM RRDGS WMG HJV ATQM MU HJV VKSCK KBFKCC OWTKSTL."
    # ciphertext_short = "AW BOMT APPA OVDLZUULVA OIZ UW RBAA WWDMYA LLZPDLL NYWT APL JWUALVA VN BOM OVDLZUMK. BV APLU BOQZ NWCMYVTMUB QZ UWA H KMTWJZHKF. QA PA VVB I ZLXBJSQJ. QA PA IU VLPWBA IYQZBVKYIJG; H OIAMMCS VTPOHZJPF VN ALF; APL TWZB PHBLNBT IYQZBVKYIJG MCMY LAAIITPAOMK VV BOM NHKL VN BOM OSWIM; HV WSQNIYKOG WM DMHTAP, DPLZL APL YQJP OVDLZU APL WWVZ. HV WSQNIYKOG WM SMHZUQUO, DPLZL APL LLBKHBLL OVDLZU APL POUWYIUB, VZ MCMU HV WSQNIYKOG WM YIJM, DPLZL APL ZIEWU YCSMZ APL HNYQJIU, UPOOB JL LVKCYMK; JBB BOQZ VTPOHZJPF VN ALF, DPPKO TIRMZ MIAPLZ, IZVBOMYA, OCZJHVK, AVVZ, BOM WSQNIYKOA WCMY APL TWAPLZ IUL APAAMYA, APL DQMM IUL LHCNPAMYA, VN MCMYG PVCZMOWSL - EOQJP WYLHQUA IST ULV AVDLZLQNVZ, IST EVULV ABJQMJBZ, KHZYQLA LPAZMUAPWU, LPAJWYL, HVK YMIMSTPWU PVAW MCMYG PVUL VN BOM VHBPWU."
    ciphertext_long = "VF IASS TWPQ XMKXFTDECA JRQ GC AUHA RFUTKG UEGPTGU UKCS TWL EFLHXBZ OU RJV VHJKINTK. KM MVKD IOGU EDOSXEMTUR ZQ GCZ A KCOFAGTQE. XA KJ CHH R GLNWSJXV. ZT PQ RL HROFUH YTZQIHQXRCN; C FPMSLLL VJKXYGVVE OU QGO; MVK MDZR YYIXTAC PYGUKMRKOIP TCCT CHMOHCIHOCF MC HNV UHAG MU HNV VSMDV; TB FLXNYTTFN CL WTHJVY, PVKIE AFG PXVV XOKLPP RWX VFOG. CE DEWMRRROW FD ESGINXUE, UWXFK TWL GUSRTHKU VVTGIL MVK IVUMTRLI, UI TCCP YC CRZGPYAJP DY XRCT, YYCGX ZYE ZYZFL KIRVS AFG YUKWIRN, KKXFI PK ECKSTVB; PAK IOGU MABUGICWF QW HXL, WWPAJ KPDSY FPAFGI, UFUKHTYQ, FJLPGED, QQEQ, HNV DSGIRPRAG FVTY VYC FCZYEG YPU HBGZVRH, VYC PWLV PUB UYJZVZVRH, QW TOSXP WVSUVFDER - LOGEY DKRGZNH YNC BXB JOKLPGZECL, RLA UQDCC GASJTJRU, RTFXZEH BKJQTGGOFN, BKJADKR, ACK TVZTEZOFN PLVF TOSXP WVKG MU HNV CHRKFL."
    # ciphertext_long2 = "LS KLXW RZMU KHFIPFQGEX REQ RQ NNCX HSYVVL HCJMXVH PVME VYI MSLKIPK HP RZI XSOOVLWH. XH XFWQ KLBC EGZGIRFORR MU RHD Y HGDSVBEAQ. ZX SW FSV E BINMFNZG. MR MU EG SBASWJ TBMQLSEIEVI; S JRXXPYJ SNZKTBGFQ QW LOB; XJV FYWR LCKIYEP SVKJXHMVYUC VZXB CKXCSPBCLCV QE MRI XEEV HP RZI XPHLI; EP SESKYJGJP HP UWENKL, AFWVG XAO PAGJ KHFIPF VYI ZSMJ. RR YPGYETTLR SD PGRVGSRE, YYIKO RZI VHNMERWH XSOOVL XJV BQRMJEPK, YV WZGE TX MDMIRVVRC GJ IEVO, OLGII DLC WCOSG VSDIU XAO YXVKTEG, KAKJK UO CFHWIIW; ZMX KLBC MDMIRVVRC GJ JIQ, UZMEY FKOCK HRXAOV, FTFXAOVQ, JLWUKRB, UFRL, RZI FPBQEPULU SOOV LLG QHDLCJ CEH CMQLITJ, DLC AKWI KRB HCLKADIPK, FJ OZCJC YSNCIFGPF - GLGUL FVWKMLK CCP WIL WQMIKOMEFW, EEV UGQGE LEFHWGVJ, MEPJMGJ WSWQWRUZSG, BAWEFVW, YFH IIUOPJASP MGDS WZGIC RSKW QW MRI FEVZSG."
    key = ""
    key_length = None
    vigenere = Vigenere(ciphertext_long, key, key_length)
    plaintext = "OF COURSE, IN ONE SENSE, THE FIRST ESSENTIAL FOR A MAN'S BEING A GOOD CITIZEN IS HIS POSSESSION OF THE HOME VIRTUES OF WHICH WE THINK WHEN WE CALL A MAN BY THE EMPHATIC ADJECTIVE OF MANLY. NO MAN CAN BE A GOOD CITIZEN WHO IS NOT A GOOD HUSBAND AND A GOOD FATHER, WHO IS NOT HONEST IN HIS DEALINGS WITH OTHER MEN AND WOMEN, FAITHFUL TO HIS FRIENDS AND FEARLESS IN THE PRESENCE OF HIS FOES, WHO HAS NOT GOT A SOUND HEART, A SOUND MIND, AND A SOUND BODY; EXACTLY AS NO AMOUNT OF ATTENTION TO CIVIL DUTIES WILL SAVE A NATION IF THE DOMESTIC LIFE IS UNDERMINED, OR THERE IS LACK OF THE RUDE MILITARY VIRTUES WHICH ALONE CAN ASSURE A COUNTRY'S POSITION IN THE WORLD. IN A FREE REPUBLIC THE IDEAL CITIZEN MUST BE ONE WILLING AND ABLE TO TAKE ARMS FOR THE DEFENSE OF THE FLAG, EXACTLY AS THE IDEAL CITIZEN MUST BE THE FATHER OF MANY HEALTHY CHILDREN. A RACE MUST BE STRONG AND VIGOROUS; IT MUST BE A RACE OF GOOD FIGHTERS AND GOOD BREEDERS, ELSE ITS WISDOM WILL COME TO NAUGHT AND ITS VIRTUE BE INEFFECTIVE; AND NO SWEETNESS AND DELICACY, NO LOVE FOR AND APPRECIATION OF BEAUTY IN ART OR LITERATURE, NO CAPACITY FOR BUILDING UP MATERIAL PROSPERITY CAN POSSIBLY ATONE FOR THE LACK OF THE GREAT VIRILE VIRTUES."
    decryption = Decryption(plaintext.lower(), "crypto")
    decryptions = vigenere.decrypt_no_key_no_length()
    assert(decryptions[0].text == decryption.text)
